name: Deploy services
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t mjic99/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true mjic99/react-test npm test

      - run: docker build -t mjic99/multi-client ./client
      - run: docker build -t mjic99/multi-nginx ./nginx
      - run: docker build -t mjic99/multi-server ./server
      - run: docker build -t mjic99/multi-worker ./worker

      - run: docker push mjic99/multi-client
      - run: docker push mjic99/multi-nginx
      - run: docker push mjic99/multi-server
      - run: docker push mjic99/multi-worker
